version: '3.5'

include:
  - traefik/docker-compose.yml
  - dozzle/docker-compose.yml
  - pihole/docker-compose.yml
  - photoprism/docker-compose.yml
  # - immich/docker-compose.yml

volumes:
  backups:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: '${RAID_MOUNT}/backup'
      o: bind
