services:
  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN}
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "./data:/data"
      - "./config:/config"
    networks:
      - proxy

networks:
  proxy:
    name: proxy
